# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Embedded-System-Portfolio-Projects/fpga-soc-learning/Phase2_Vitis/project_1p2_01_gpio_led/project_1p2_01_gpio_led.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
# IP: The module: 'design_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Embedded-System-Portfolio-Projects/fpga-soc-learning/Phase2_Vitis/project_1p2_01_gpio_led/project_1p2_01_gpio_led.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Embedded-System-Portfolio-Projects/fpga-soc-learning/Phase2_Vitis/project_1p2_01_gpio_led/project_1p2_01_gpio_led.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
# IP: The module: 'design_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Embedded-System-Portfolio-Projects/fpga-soc-learning/Phase2_Vitis/project_1p2_01_gpio_led/project_1p2_01_gpio_led.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
